export default {
    header: 'header',
    map: 'map',
    visualContainer: 'visual-container',
    mapCountry: 'map-country',
    temperatureBar: 'temperature-bar',
    selected: 'selected',
    colorCodeUl: 'color-code-ul',
    colorCodeli: 'color-code-li',
    colorBox: 'color-box',
    rangeLabel: 'range-label',
    colorCodeDiv: 'color-code-div',
    noDataLabel: 'no-data-label',
    progressDiv: 'progress-div',
    progressBar: 'progress-bar',
    progressButton: 'play-pause-btn',
    hideIcon: 'hide-icon',
    mapToolTip: 'map-tooltip',
    lineChart: 'line-chart',
    barChartContainer: 'bar-chart-container',
    barChartXaxis: 'bar-chart-x-axis',
    barChartYaxis: 'bar-chart-y-axis',
    barGroup: 'bar-group',
    barContainer: 'bar-container',
    barRect: 'bar-rect',
    barTitle: 'bar-title',
    barValue: 'bar-value'
}